{% set version = "1.2.6" %}

package:
  name: pytoolconfig
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytoolconfig/pytoolconfig-{{ version }}.tar.gz
  sha256: f2d00ea4f8cbdffd3006780ba51016618c835b338f634e3f7f8b2715b1710889

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0

requirements:
  host:
    - pip <22
    - pdm
    - pdm-pep517 >=1.0.5
    - python >=3.7
  run:
    - packaging >=22.0
    - python >=3.7
    - tomli >=2.0.1
    - typing-extensions >=4.4.0

test:
  imports:
    - pytoolconfig
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pytoolconfig
  summary: Python tool configuration
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
